## COMPUTER VISION PROJECT1

**Because of Colabs RAM size, all cells are not executed at once.**

In [1]:
%tensorflow_version 2.x
import tensorflow
tensorflow.__version__

'2.6.0'

In [2]:
#import the random seed generator
import random
random.seed(0)

#ignore the warnings
import warnings
warnings.filterwarnings('ignore')

In [3]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [1]:
#Importing the required libraries
import numpy as np
import pandas as pd
import cv2
import glob
import matplotlib.pyplot as plt
%matplotlib inline
from sklearn.model_selection import train_test_split
import pickle

In [5]:
#importing the os library and getting the input folders in the given path
import os
Input_path='/content/gdrive/MyDrive/Colab Notebooks/CV_Notebooks/Part-1 - Plant Seedling Classification Data/train'
label_folders=os.listdir(Input_path)
print(label_folders)

['Black-grass', 'Charlock', 'Cleavers', 'Common Chickweed', 'Common wheat', 'Fat Hen', 'Loose Silky-bent', 'Maize', 'Scentless Mayweed', 'Shepherds Purse', 'Small-flowered Cranesbill', 'Sugar beet']


Total there are 12 folders of 12 different seedling types. All images from the folders have to be considered

In [34]:
#The resized image rows and columns
img_rows=128
img_cols=128

**Resizing of each image and storing into array**

In [7]:
#array to store the features and labels of images in the folders
x_y_features=[]

for label_folder in label_folders:
  folder_path=os.path.join(Input_path,label_folder)
  for img_path in glob.glob(os.path.join(folder_path,"*.png")):
    image=cv2.imread(img_path,cv2.IMREAD_COLOR)
    image_resized=cv2.resize(image,(img_rows,img_cols))
    x_y_features.append([image_resized,label_folder])

Pickling the features to avoid loss of data

In [8]:
import pickle
pickle_data=open('image_data.pkl','wb')
pickle.dump(x_y_features,pickle_data)
pickle_data.close

<function BufferedWriter.close>

In [9]:
x_y_features[0]

[array([[[ 24,  47,  77],
         [ 33,  54,  81],
         [ 45,  66,  89],
         ...,
         [ 55,  78,  88],
         [ 60,  86,  94],
         [ 52,  83,  90]],
 
        [[ 21,  46,  79],
         [ 36,  57,  86],
         [ 46,  66,  90],
         ...,
         [ 59,  77,  88],
         [ 62,  81,  92],
         [ 57,  77,  89]],
 
        [[ 24,  49,  82],
         [ 31,  54,  84],
         [ 50,  69,  95],
         ...,
         [ 57,  72,  84],
         [ 58,  72,  85],
         [ 61,  77,  89]],
 
        ...,
 
        [[155, 149, 143],
         [156, 150, 144],
         [154, 149, 143],
         ...,
         [142, 136, 132],
         [ 97,  92,  91],
         [ 67,  61,  67]],
 
        [[155, 149, 142],
         [156, 150, 142],
         [152, 147, 141],
         ...,
         [140, 135, 130],
         [ 93,  87,  87],
         [ 60,  54,  59]],
 
        [[156, 149, 142],
         [155, 149, 141],
         [153, 147, 139],
         ...,
         [140, 133, 129],
  

The below code is commented and to use only colab connection is lost

In [2]:
unpickle_data=open('image_data.pkl','rb')
img_unpickle=pickle.load(unpickle_data)
unpickle_data.close

<function BufferedReader.close>

In [3]:
x_y_features=img_unpickle

Checking the total number of samples and shuffling the data

In [4]:
len(x_y_features)

4767

In [5]:
import random
random.seed(0)
random.shuffle(x_y_features)

In [67]:
x_y_features[0:2]

[[array([[[ 44,  62,  84],
          [ 54,  76,  92],
          [ 34,  72,  79],
          ...,
          [ 67,  80,  96],
          [ 86,  99, 109],
          [ 88, 103, 114]],
  
         [[ 60,  75,  95],
          [ 80, 100, 111],
          [ 20,  81,  70],
          ...,
          [ 63,  78,  97],
          [ 62,  75,  92],
          [ 35,  49,  67]],
  
         [[ 50,  71,  89],
          [ 35,  74,  75],
          [ 30,  88,  75],
          ...,
          [ 93, 108, 119],
          [ 64,  80,  98],
          [ 70,  90, 103]],
  
         ...,
  
         [[102,  95,  99],
          [ 84,  79,  85],
          [ 92,  85,  89],
          ...,
          [ 54,  51,  58],
          [ 52,  49,  56],
          [ 49,  47,  53]],
  
         [[105, 101, 107],
          [106,  99, 105],
          [110, 104, 110],
          ...,
          [ 52,  48,  55],
          [ 54,  47,  52],
          [ 54,  50,  56]],
  
         [[ 80,  71,  77],
          [111, 105, 115],
          [120, 116, 122

In [6]:
image_data=pd.DataFrame(x_y_features,columns=['image','label'])

In [7]:
#Deleting the not needed data to clear memory
del(x_y_features)

In [70]:
image_data.head()

image                      label
0  [[[44, 62, 84], [54, 76, 92], [34, 72, 79], [1...                 Sugar beet
1  [[[61, 66, 78], [50, 55, 66], [52, 57, 66], [5...                   Charlock
2  [[[197, 189, 184], [199, 192, 186], [197, 190,...                    Fat Hen
3  [[[162, 160, 155], [162, 158, 153], [169, 162,...  Small-flowered Cranesbill
4  [[[51, 68, 85], [50, 67, 85], [54, 68, 85], [5...  Small-flowered Cranesbill

In [8]:
X_raw=np.array(image_data.image)
y_raw=image_data.label

In [9]:
del(image_data)

In [10]:
X_raw[0].shape

(128, 128, 3)

**Normalizing the data**

In [11]:
X_raw /= 255.0

In [12]:
X_raw[0].shape

(128, 128, 3)

**Label encoding the output values**

In [13]:
from sklearn.preprocessing import LabelEncoder
label_encode=LabelEncoder()
seed_encoded=label_encode.fit_transform(y_raw)
Label_values=pd.DataFrame(seed_encoded,columns=['encoded_value'])
Label_values['labels']=y_raw
print(seed_encoded)

[11  1  5 ...  1  8  8]


In [14]:
seed_encoded=np.array(seed_encoded)
y_raw=np.array(y_raw)

In [15]:
Label_values.drop_duplicates('labels',inplace=True)

In [16]:
Label_values

encoded_value                     labels
0              11                 Sugar beet
1               1                   Charlock
2               5                    Fat Hen
3              10  Small-flowered Cranesbill
5               6           Loose Silky-bent
8               0                Black-grass
10              3           Common Chickweed
14              8          Scentless Mayweed
17              9            Shepherds Purse
18              4               Common wheat
19              7                      Maize
20              2                   Cleavers

**Converting to categorical data**

In [17]:
from tensorflow.keras.utils import to_categorical
y=to_categorical(seed_encoded,num_classes=None,dtype='int')

In [82]:
y[0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

##Supervised Learning

**Flattening the each image data to train supervised model**

In [18]:
x_flatten=[]
for k in range(len(X_raw)):
  x_flatten.append(X_raw[k].flatten())

In [19]:
x_flatten=np.array(x_flatten)
x_flatten[0]

array([0.17254902, 0.24313725, 0.32941176, ..., 0.20784314, 0.19215686,
       0.22352941])

**Splitting into Train and test data**

In [20]:
x_train,x_val,y_train,y_val=train_test_split(x_flatten,seed_encoded,test_size=0.3,random_state=0)

In [21]:
print(x_train.shape,y_train.shape)

(3336, 49152) (3336,)


**Logistic regresion model**

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
log_model=LogisticRegression(multi_class='ovr',random_state=0,max_iter=10000)
log_model.fit(x_train,y_train)

In [30]:
print("Train accuracy:",accuracy_score(y_train, log_model.predict(x_train)))

0.9973021582733813


In [31]:
print("Test accuracy:"accuracy_score(y_val, log_model.predict(x_val)))

0.4479385045422781


Train accuracy is more, but test accuracy is less. So it is overfit

In [22]:
#from xgboost import XGBClassifier
#xgb_model=XGBClassifier(learning_rate=0.01)
#xgb_model.fit(x_train,y_train)

In [ ]:
#Train and test accuracy
#print("Train accuracy:",accuracy_score(y_train, xgb_model.predict(x_train)))
#print("Test accuracy:"accuracy_score(y_val, xgb_model.predict(x_val)))

**Using Neural Networks**

In [19]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten
from tensorflow.keras import regularizers, optimizers

In [20]:
#Converting the output values to categorical data
y_train=to_categorical(y_train,num_classes=None,dtype='int')
y_val=to_categorical(y_val,num_classes=None,dtype='int')

In [21]:
model=Sequential()

#flattening the inputs array
model.add(Flatten())

#Adding the dense layers with activation as relu
model.add(Dense(512,activation='relu'))
model.add(Dense(128,activation='relu'))
model.add(Dense(64,activation='relu'))

#Adding the softmax as activation in the last layer
model.add(Dense(12,activation='softmax'))
sgd=optimizers.Adam(learning_rate=1e-4)
model.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [22]:
model_hist=model.fit(x_train,y_train,epochs=30,batch_size=32,validation_data=(x_val,y_val),verbose=1)

Epoch 1/30
105/105 [==============================] - 18s 160ms/step - loss: 3.7228 - accuracy: 0.1262 - val_loss: 2.9310 - val_accuracy: 0.0957
Epoch 2/30
105/105 [==============================] - 16s 155ms/step - loss: 2.3861 - accuracy: 0.2212 - val_loss: 2.2467 - val_accuracy: 0.2355
Epoch 3/30
105/105 [==============================] - 17s 158ms/step - loss: 2.1598 - accuracy: 0.2530 - val_loss: 2.1307 - val_accuracy: 0.2739
Epoch 4/30
105/105 [==============================] - 16s 155ms/step - loss: 2.0553 - accuracy: 0.3022 - val_loss: 2.0413 - val_accuracy: 0.3354
Epoch 5/30
105/105 [==============================] - 16s 155ms/step - loss: 1.9769 - accuracy: 0.3231 - val_loss: 1.9622 - val_accuracy: 0.2984
Epoch 6/30
105/105 [==============================] - 16s 155ms/step - loss: 1.9272 - accuracy: 0.3288 - val_loss: 1.9972 - val_accuracy: 0.3089
Epoch 7/30
105/105 [==============================] - 16s 156ms/step - loss: 1.7363 - accuracy: 0.4086 - val_loss: 2.2643 - val_ac

In [23]:
train_score=model.evaluate(x_train,y_train,verbose=0)
test_score=model.evaluate(x_val,y_val,verbose=0)
print("Train_score:",train_score,"\nTest_score:",test_score)

Train_score: [0.987899899482727, 0.6115108132362366] 
Test_score: [1.8379061222076416, 0.4437456429004669]


The training accuracy and test accuracy are increased compared to supervised learning scores

**Using CNN**

In [24]:
x_train,x_val,y_train,y_val=train_test_split(x_flatten,y,test_size=0.3,random_state=0)

In [25]:
from tensorflow.keras.layers import Conv2D,Dropout,MaxPooling2D

model1=Sequential()

#Adding the convolution layer and max pool layers
model1.add(Conv2D(32,kernel_size=3,activation='relu',input_shape=(128,128,3)))
model1.add(MaxPooling2D(pool_size=2))

model1.add(Conv2D(32,kernel_size=3,activation='relu',padding='same'))
model1.add(MaxPooling2D(pool_size=2))

model1.add(Conv2D(64,kernel_size=3,activation='relu',padding='same'))
model1.add(MaxPooling2D(pool_size=2))
#model1.add(Dropout(0.2))

#Flattening the inputs before passing to neural network
model1.add(Flatten())


model1.add(Dense(512,activation='relu'))
model1.add(Dropout(0.5))

model1.add(Dense(128,activation='relu'))
model1.add(Dropout(0.5))

model1.add(Dense(12,activation='softmax'))

In [26]:
model1.compile(loss='categorical_crossentropy',optimizer='Adam',metrics=['accuracy'])

In [27]:
x_train=x_train.reshape(x_train.shape[0],128,128,3)
x_val=x_val.reshape(x_val.shape[0],128,128,3)

In [28]:
#Checking the input shape
x_train.shape

(3336, 128, 128, 3)

In [29]:
model1_hist=model1.fit(x_train,y_train,batch_size=64,epochs=20,validation_data=(x_val,y_val),initial_epoch=0)

Epoch 1/20
53/53 [==============================] - 74s 1s/step - loss: 2.4489 - accuracy: 0.1322 - val_loss: 2.3783 - val_accuracy: 0.1572
Epoch 2/20
53/53 [==============================] - 72s 1s/step - loss: 2.1510 - accuracy: 0.2626 - val_loss: 1.7512 - val_accuracy: 0.3864
Epoch 3/20
53/53 [==============================] - 72s 1s/step - loss: 1.7239 - accuracy: 0.3966 - val_loss: 1.7233 - val_accuracy: 0.4228
Epoch 4/20
53/53 [==============================] - 72s 1s/step - loss: 1.4767 - accuracy: 0.4997 - val_loss: 1.1508 - val_accuracy: 0.6024
Epoch 5/20
53/53 [==============================] - 73s 1s/step - loss: 1.2641 - accuracy: 0.5650 - val_loss: 1.0536 - val_accuracy: 0.6576
Epoch 6/20
53/53 [==============================] - 74s 1s/step - loss: 1.1546 - accuracy: 0.5959 - val_loss: 0.9953 - val_accuracy: 0.6548
Epoch 7/20
53/53 [==============================] - 73s 1s/step - loss: 1.0529 - accuracy: 0.6400 - val_loss: 0.8786 - val_accuracy: 0.7023
Epoch 8/20
53/53 [==

In [30]:
train_score=model1.evaluate(x_train,y_train,verbose=0)
test_score=model1.evaluate(x_val,y_val,verbose=0)
print("Train_score:",train_score,"\nTest_score:",test_score)

Train_score: [0.128966823220253, 0.9532374143600464] 
Test_score: [0.6799948811531067, 0.7966457009315491]


**Pickling the model**

In [32]:
#Serialize model to json
from tensorflow.keras.models import model_from_json
model_json=model1.to_json()
with open("Model1.json","w") as json_file:
  json_file.write(model_json)

#Serialize weights to h5
model1.save_weights("model1.h5")
print("Saved to disk")

Saved to disk


**Predicting the image**

In [35]:
Test_image_path="/content/gdrive/MyDrive/Colab Notebooks/CV_Notebooks/Prediction/Predict.png"
Test_image=cv2.imread(Test_image_path,cv2.IMREAD_COLOR)

Test_image_resized=cv2.resize(Test_image,(img_rows,img_cols))

In [36]:
Test_array=np.array(Test_image_resized)

In [40]:
Test_array=Test_array.reshape(1,128,128,3)

In [41]:
model1.predict(Test_array)

array([[0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

As per the model, Common Chikweed is predicted